---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgA9QM1fJsBuLhMkimgKsEXxp2p9aLSH7dM1PYObPZbeVXp6z/X5zonBHLVVeUw5iknjPTnvmuExf/gqMbsgLAv+8cm0tRK3v4gg3kUKwBpzymlIluQ7f09zveHe4e1TcLqy/Eh4vMDg4A9wL1sstY4mf4Sy434Fjfre6h7Ar/9Onpo85cqZqDcfEHr0GFgl92xzVqoXFgegsPcEBvoBLX9gHZ00K2bbxkL4AZMLXECQbRKVV4ffGK8kgcOV6CxajzHOGE0OROzSSfHGVxo6C0EdMnfwFIMjP8+kEGwr6BUftqzFItjN2mF2/REiYEl7OiDqFGy9nEYYqD3HPmDRIR59hx/TyjcTrMGzffvqepJn5fCOpx3ecLUOA4BzYTyNMYO7DEIV+4ni9nl5cByItagFeyzFuiTGM2yZfjC7QVFolJwJUyybG9z9srEyFDY/u61YJhVOYU/HqpIIohgbGDJSx5R5RefWE0srSvBKbKPB+qTkqwrKONyLHkwqXtc+MCkTcGKlSUDxXfob0DnVj5FTYILAcNVy8rWh/G/tRoPhKbXfAovmaVvTz7EJ/N498IF0zFyuXbEZX34Rg/koOvNma10TDBR2869d5qssjpRg8yIyZYhwoPpGHOHZ78jyMol3EenrPQPEmZyEXxV+h07cMQZ2Pg/6v5oQDCjEOBq05iVoBOkHyM1U2oXiD/EQOeu/t5FyQHQpXrafaOYf/98Abw1v0B1O6vTCtvdPYxoIWOH1U8R/Sy0wdnmadQ==
    username: AgAehJX79XoEqzPNq9C1ZDJjXwGURkChatYnBfksyxgW7MnDEuBKT1E4PlxPngsXx1eLlN6x+wQD3s0QqVL5Yiz1lc0RM10zoNARtFUbVjasTqP/crOg6GIHLkuIxcMNEG4hIJgWi/Zg77p4/Ljo3yknWXDlsmupi/4luYYV9tTQ9DUV8396MWXViaGYB8/9+vmPP0q+ScrsO22FUMFiJZBzgLz4koY4m8Mvim6XayE3fNtacbv3Yd3U+Ltlwb65pFw8uYIUNAmCgSJOjkt+3/j456tfeyjhNG/1hgM3X7FISnmgC5Sqi478LdiY7/jUYmgosQdo5/ktfg5GP+RfAvPVrFC+XAS7Rj77qbsV4iy+YJTTxEprVRVaB1VGGL7lFNn6e06qf51f8h8tda1jO9chrhvMC+1tBtbmmBuxihaKfvHINDZFkW6+rDBSnoS8zHtu5+BeAxaoXMfXtxePsoM2LpqLmfTSE/iwBt6ExTeIf46Y5gwoXHExL7IondzVvhZx3dlynqTH8pa4xCfmDSz+eVckxChwAo+YlhPMt2mpZLRdil4OXfF6oKrZdpu//BgBCm6oce44S0juozHflq42w34jDbJR9Ii4sQ3DaEv8It4yGCEBbQ++SdiYfGniU0m+PsyDFCQemT6mWptD90Y8H0TM15eNzJiIpVtG3YFPhE7SM68ingOH6O59ZXKd7nC7XWFr
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: default
